### ISSUE TITLE
Finish producing posters for promoting committee

### ISSUE THREAD

**Issue by justwheel** [Women-in-Computing-at-RIT/allies-tasks#1]
# Summary

In recent meetings, we have been working on producing a poster to hang up for promoting the Allies Committee (shown at the bottom).
# Analysis

By now, the poster has mostly been finished in terms of design. From here, our next steps are to begin working on distribution. We can share them among committee members to hang up and post around and hopefully anticipate greater turnout at coming meetings.

One remaining thing we need to do is get confirmation about where we can print them within WiC.
# Implementation
1. Figure out where to print the posters (The Hub? In Golisano? etc.)
2. Print 50 posters and bring to the next Allies meeting
3. Distribute to Committee members to hang across campus (most in Golisano, some in tunnels, some in other colleges)
4. Watch for form responses on the form linked in the poster tabs
# Poster

[wic-allies-poster.pdf](https://github.com/Women-in-Computing-at-RIT/allies-tasks/files/552173/wic-allies-poster.pdf)

**Comment by amccarthy1** [comment]
The posters have been printed! Right now the pull-tabs are being cut, but they should be ready by Thursday. I'll let everyone know via slack and email when they're finished and we can start hanging them up.

**Comment by justwheel** [comment]
@amccarthy1 Woohoo, awesome! Then I will be sure to swing by on Thursday to grab some (I still have more posters to hang up, so I can do the "two birds, one stone" thing). You can go ahead and pencil me in for the residential tunnels.

**Comment by justwheel** [comment]
Whooo, this is completed! Posters are hung up around campus. :smile:
