### ISSUE TITLE
Create Agenda for Week 1 Meeting

### ISSUE THREAD

**Issue by amccarthy1** [Women-in-Computing-at-RIT/allies-tasks#3]
# Summary
One of our goals for Spring Semester was to have an agenda for every meeting. Another goal was to start off during Week 1 so we can get up and running ASAP. Thus, we should finish our week 1 agenda before the semester so we can have a great first meeting!

# Implementation
As with last semester, we'll put the agendas in our Google Drive "agendas" folder. I've already created a folder for 2016-2017 Spring.

# Other Information
Our goals for the first few meetings are outlined in the final meeting notes of last semester, and we should try to hit as many of them as possible.

**Comment by justwheel** [comment]
Do we have the notes from the last meeting available anywhere? I know we did something with them but I can't remember where.

**Comment by amccarthy1** [comment]
The notes from last semester are available on the drive at  
**WiC Allies > Agendas and Meeting Notes > 2016-2017 Fall**

Also, I finished this, but I forgot to close it.
